### ISSUE TITLE
Command 'php artisan migrate' doesn't create a tables in database (.env file correctly set)

### ISSUE THREAD

**Issue by martyxo** [VarghaSabee/t-shirt_designer#1]
Hello Vargha!
I have some problem. If I use command php artisan migrate - this doesn't works and doesn't creates a DB table. Output from command line in Windows is here: [http://www.img.tpx.cz/uploads/57544678_609632552837817_8712774771244269568_n.png](url)
And localhost's url tell me this error: [http://www.img.tpx.cz/uploads/57326279_451601715587672_5861483942074384384_n.png](url)
Can you help me, please?

**Comment by VarghaSabee** [comment]
Of course. Can I ask you to upload the outputs are, the images not available. What kind of database do you use which version?

**Comment by sabolch** [comment]
Hi , @martyxo!
Of course. Can I ask you to upload the outputs, the images not available. I commited some changes please check it out.
